# Generated by Django 4.1.7 on 2023-04-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test2023", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="stockList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stockId", models.CharField(max_length=4)),
                ("stockName", models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(name="Book",),
    ]
