# Generated by Django 4.1.7 on 2023-04-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test2023", "0003_remove_stocklist_id_alter_stocklist_stockid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocklist",
            name="stockId",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
